### PR TITLE
alert feature added

### PR DESCRIPTION
**Pull request by shrisantadhikari**
I think that alert feature you must  check because makes sure that  the user really want to change the color . because  sometimes user click mistakely .

### CODE REVIEW

**Comment by codewithshreesant** [comment]
Ok you are right. please add another  button that can can increase the size of the tex. increase size with 10px in each click.

**Comment by shrisantadhikari** [comment]
Can I add one alert before changing the font size

**Comment by codewithshreesant** [comment]
I think That alert feature can make user frusted in each click while changing 10 px font-size.

**Comment by shrisantadhikari** [comment]
Yah you are right , I dont include  alert feature .

**Pull request merged**
